# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chengfang Liu
title: Senior Full Stack Web Developer
email: lcf800@gmail.com
website: https://liucf.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: ABOUT ME
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chengfang Liu and I'm a senior Full Stack web developer engineer. 15 years of software development experience and 10+ years of full-stack experience, with multinational cooperation project background and excellent coding and system design skills; good at page layout and refactoring and strong ability to identify and design common frameworks and modules, especially proficient in Laravel ecosystem.

content:
  - title: SKILLS
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming languages: PHP, C#, Javascript, JAVA, Python, R, Swift, Latex, Markdown
      - Framework: Laravel, Vue, React, Flutter, Next.js, React Native, TailwindCSS, AlplineJS, Livewire
      - Testing: Unit Test, Integrated Test, Browser Test
      - Front End: HTML, CSS, Gulp, Sass, Less, Webpack, PostCSS
      - Databases: MySQL, PgSQL, PDO, SQLite, SQL Server
      - Version Control/ CodeBase: Svn, Git, CI, PHPDoc, Packagist, Npm, Rubygems
      - Data Analysis: Python, R, IMB SPSS

  - title: WORK EXPERIENCE # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Waikato
        quote: >
          03/2023 - Present  /  Research Programmer of Artificial Intelligence Institute (Casual Contract)  /  Hamilton, New Zealand
        description: | # this will include new lines to allow paragraphs
          - Assist with the programming for a machine learning related academic research project as a programmer.
      - layout: top-middle
        title: Internet Media Publications
        quote: >
          06/2008 - 02/2023  /  Full Stack Developer  /  Remote
        description: | # this will include new lines to allow paragraphs
          - Worked closely with USA's development team to design, build and operate highly secure feasible technical solutions, and upgraded and improved the technology stack according to the project requrements.
          - Managed the complete software development process from conception to deployment.
          - Upgraded the software following deployment, and built efficient interfaces and page interactions.
          - Analyzed the project requirements, and worked with team members in the USA to customize solutions.
          - Prepared technical documentation, including technical solutions, user manuals, and test reports.
      - layout: top-middle
        title: Shanghai DingRen Technology Co., LTD
        # link: github.com/sproogen
        # link_text: 05/2012 - Present  / Remote
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title: 05/2012 - Present / Remote
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          06/2007-06/2008  /  Software Engineer  /  Shanghai, China
        description: | # this will include new lines to allow paragraphs
          - Participated in and managed the development and maintenance of the Encrypted Media Sales Platform.
          - Complete the high-quality coding, and analyzed the development technology research involved in the project.
          - Discussed product requirements in-depth, defined product features, and reproduced existing Windows media platform to create new functions using Javascript Language.
          - Conducted the Multi-Server Distributed Deployment Project, communicated with the parent company (Tencent), executed project research, formulated the platform deployment plan, and completed the smooth transition of the system and improved user experience.

  - title: PROJECT EXPERIENCE # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Online Video Membership System
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer
        description: | # this will include new lines to allow paragraphs
          Project Description: A video/image membership sales site developed using the Laravel framework, with a membership of $29.90 per month and unlimited access to all content within site.
          - Discussed project requirements with project leaders from USA companies and controlled the project schedule.
          - Designed the program according to the project requirements, including front-end& back-end full-stack development.
          - Analyzed the initial pure PHP version and the upgrade/update requirements of the Codeigniter framework.
          - Completed the application of the latest technologies such as Laravel, Vue, Tailwindcss, etc. and integrated various online payment systems.
          - Summarized the core data indicators of the website, analyzed the causes of data fluctuations and specified SEO optimization solutions.

      - layout: top-middle
        title: Vacation travel booking website
        link: https://www.thecaboagency.com
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer 
        description: | # this will include new lines to allow paragraphs
          Project Description
          The website was developed using PHP, customers can book travel packages online, and the system automatically generates reminders to company staff and related service providers. The website also supports an online booking payment system. 

          - Analyzed and discussed project requirements, solutions and planning with project leaders in USA companies.
          - Managed the full-stack development of the front-end and back-end of the project, tested the project operation and reported the project development progress at different stages.
          - Designed the page and realized all functions through PHP, JavaScript, and CSS, including the function to automatically generate PDF files and send reminders to administrators and travel service providers after successful booking and payment.

      - layout: top-middle
        title: WeChat Mini Program (Lucky Cat Draw)
        link: https://ibc168.net
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer 
        description: | # this will include new lines to allow paragraphs
          Project Description: Developed a WeChat Mini Program - "Lucky Cat Draw" for a Japanese company. The Mini Program is calledAPI to read the background data and present it to the user, who can use the Mini Program to draw a lottery.
          - Communicated with the Japanese project team and planned the function and layout of the Mini Program.
          - Designed and developed the front-end pages of the Mini Program according to the preference and positioning of the customers using Tencent's WeChat native development language and tools.
          - Laravel and Nova frameworks were used for the back-end management side, supporting multi-role administrators with different permissions for system management.
          - The Mini Program completes different functions by calling APIs, including membership level, recommendation mechanism, lottery rules, data analysis, etc.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: EDUCATION # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: University of Waikato
        caption: 2023.01 / Waikato, New Zeanland
        sub_title: Master of Information Technology
      
      - layout: left
        title: International Christian University
        caption: 2018.09 - 2020.06 / Tokyo, Japan
        sub_title: Master of Public Economy

      - layout: left
        title: Hunan University
        caption: 2003.09 - 2007.06 / Changsha, China
        sub_title: Bachelor of Software Engineering

        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
