# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Liu
title: Senior Full Stack Web Developer
email: lcf800@gmail.com
website: https://liucf.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Michael Liu and I'm a senior Full Stack web developer engineer. 15 years of software development experience and 10+ years of full-stack experience, with multinational cooperation project background and excellent coding and system design skills; Good at page layout and refactoring and strong ability to identify and design common frameworks and modules.

content:
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming languages: PHP, C#, Javascript, JAVA, Python, R, Swift, Latex, Markdown
      - Framework: Laravel, Vue, React, Flutter, Next.js, React Native, TailwindCSS, AlplineJS, Livewire
      - Testing: Unit Test, Integrated Test, Browser Test
      - Front End: HTML, CSS, Gulp, Sass, Less, Webpack, PostCSS
      - Databases: MySQL, PgSQL, PDO, SQLite, SQL Server
      - Version Control/ CodeBase: Svn, Git, CI, PHPDoc, Packagist, Npm, Rubygems
      - Data Analysis: Python, R, IMB SPSS

  - title: PROFESSIONAL EXPERIENCE # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Internet Media Publications
        # link: github.com/sproogen
        # link_text: 05/2012 - Present  / Remote
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title: 05/2012 - Present / Remote
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer  /  05/2012 - Present  /  Remote
        description: | # this will include new lines to allow paragraphs
          - Worked closely with USA's development team to design, build and operate highly secure feasible technical solutions, and upgraded and improved the technology stack according to the project requrements.
          - Managed the complete software development process from conception to deployment.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Online video membership system
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer
        description: | # this will include new lines to allow paragraphs
          Long-term project. A video/picture membership sales website developed using the Laravel framework (memberships $19.9 per month, unlimited viewing of all content on the website), produced for American companies, operated and servers are in the United States, and independently implements all front and back functions.

          Discuss the requirements with the person in charge of the American company. They are responsible for providing the design (PSD) files, and I am responsible for the program design. From the original pure PHP version, to the later use of the Codeigniter framework, now the Laravel framework is used. Many versions have been iterated. The website is now operating stably. Last month, the number of visits was 200K, which is able to maintain a stable income.

      - layout: top-middle
        title: Vacation travel booking website
        link: https://www.thecaboagency.com
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer
        description: | # this will include new lines to allow paragraphs
          Project Introduction：
          Long-term project. Use PHP language to develop an online travel reservation website system for American travel companies. Including front and back ends and payment functions. The operations and servers are in the United States, and all front and back functions are implemented independently. 

          My responsibility：
          Discuss the requirements with the person in charge of the American company. They are responsible for providing the requirements, and I am responsible for the program design. I have been iteratively updated many times, and have been using pure PHP language development.

      - layout: top-middle
        title: Online data storage service
        link: https://bestwns.com
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer
        description: | # this will include new lines to allow paragraphs
          The online data storage system (member fee system) developed using the Laravel framework is produced for American companies, and the operations and servers are all located in the United States. I did all the front and back functions independently. After the system went online, the operation effect was not good, but the front-end and back-end functions have been completed, including the integration of Stripe in the payment system.

      - layout: top-middle
        title: WeChat Mini Program (Lucky Cat Draw)
        link: https://ibc168.net
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Full Stack Developer
        description: | # this will include new lines to allow paragraphs
          WeChat Mini Program developed for a Japanese company. The main function is to put the lottery products on the shelves, including rich functions such as membership level, referral mechanism, lottery rules, data analysis and so on. Customers provide requirements, and I am responsible for the design and development of the front and back ends. Zeplin was used for the design of the applet, and the native development language of WeChat was used for development. The back-end management system and API use Laravel framework and Nova. Now the system has just been completed and launched, the back-end address is https://ibc168.net/, and you can find it by searching in the mini program WeChat.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: International Christian University
        caption: 2018.09 - 2020.06 / Tokyo, Japan
        sub_title: Master of Public Economy

      - layout: left
        title: Hunan University
        caption: 2003.09 - 2007.06 / Changsha, China
        sub_title: Bachelor of Software Engineering

        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
